title: Alexander Messejnikov
description: "&#8226; (204) 510-9816<br>&#8226; messejnikovalexander@gmail.com<br>&#8226; Winnipeg, MB<br>&#8226; <a href=\"https://www.linkedin.com/in/alex-messejnikov\">LinkedIn</a>"

theme: jekyll-theme-minimal
