title: Alexander Messejnikov
description: "(204) 510-9816<br>messejnikovalexander@gmail.com<br><a href=\"https://www.linkedin.com/in/alex-messejnikov\">linkedin.com/in/alex-messejnikov</a><br>Winnipeg, MB"

theme: jekyll-theme-minimal
